/**
 * Loads verified AllHomes market price data for Australian suburbs.
 * Generated by scripts/scrape-suburb-prices.ts
 */

import { readFileSync } from "fs";
import { join } from "path";

export interface SuburbPriceData {
  suburb: string;
  state: string;
  postcode: string;
  totalListings: number;
  pricedListings: number;
  cheapest: number | null;
  mostExpensive: number | null;
  median: number | null;
  prices: number[];
  scrapedAt: string;
}

interface PriceDatabase {
  generatedAt: string;
  totalSuburbs: number;
  withPriceData: number;
  suburbs: SuburbPriceData[];
}

let cached: PriceDatabase | null = null;

function loadDatabase(): PriceDatabase {
  if (cached) return cached;
  try {
    const filePath = join(process.cwd(), "data", "suburb-prices.json");
    const raw = readFileSync(filePath, "utf-8");
    cached = JSON.parse(raw) as PriceDatabase;
    console.log(`[suburb-prices] Loaded ${cached.suburbs.length} suburbs (${cached.withPriceData} with price data)`);
    return cached;
  } catch {
    console.warn("[suburb-prices] Could not load data/suburb-prices.json");
    return { generatedAt: "", totalSuburbs: 0, withPriceData: 0, suburbs: [] };
  }
}

/**
 * Look up verified market price data for a suburb.
 */
export function getSuburbPrices(suburb: string, state?: string): SuburbPriceData | null {
  const db = loadDatabase();
  const key = suburb.toLowerCase().trim();
  return db.suburbs.find(
    (s) => s.suburb.toLowerCase() === key && (!state || s.state === state.toUpperCase())
  ) ?? null;
}

/**
 * Get the correct budget tier for a suburb based on verified median prices.
 */
export function getVerifiedBudgetTier(suburb: string, state: string): string | null {
  const data = getSuburbPrices(suburb, state);
  if (!data?.median) return null;
  if (data.median <= 500_000) return "under500k";
  if (data.median <= 750_000) return "from500kTo750k";
  if (data.median <= 1_000_000) return "from750kTo1M";
  if (data.median <= 1_500_000) return "from1MTo1_5M";
  return "above1_5M";
}

/**
 * Find suburbs in a state within a budget range, sorted by median price.
 */
export function findAffordableSuburbs(
  state: string,
  maxBudget: number,
  minListings: number = 2
): SuburbPriceData[] {
  const db = loadDatabase();
  return db.suburbs
    .filter((s) =>
      s.state === state.toUpperCase() &&
      s.pricedListings >= minListings &&
      s.cheapest !== null &&
      s.cheapest <= maxBudget
    )
    .sort((a, b) => (a.median ?? 0) - (b.median ?? 0));
}

/**
 * Get all suburbs with price data for a state.
 */
export function getStateSuburbs(state: string): SuburbPriceData[] {
  const db = loadDatabase();
  return db.suburbs
    .filter((s) => s.state === state.toUpperCase() && s.pricedListings > 0)
    .sort((a, b) => (a.median ?? 0) - (b.median ?? 0));
}

/**
 * Summary stats for logging.
 */
export function getPriceDatabaseStats(): { total: number; withData: number; generatedAt: string } {
  const db = loadDatabase();
  return { total: db.totalSuburbs, withData: db.withPriceData, generatedAt: db.generatedAt };
}
